### ISSUE TITLE
Doesn't compile because of missing files

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [g4klx/AMBETools#2]
The project file won't compile because it seems to be missing some header files and possibly a lot more..

sndfile.h can't be found, nor can imbe_vocoder.h and IMBEFEC.h and probably other files.

What else needs to be installed so this can be compiled ?

**Comment by g4klx** [comment]
Hi Roger
According to the README file, you need libsndfile to be installed on your system. Then you need to ensure that imbe_vocoder is also clones from my GitHub area, and installed at the same level in the directory structure as AMBETools, and of course made using make. Then you should be able to do a make of AMBETools and it should build.
Jonathan  G4KLX

    On Sunday, 24 May 2020, 01:42:10 BST, Roger Clark <notifications@github.com> wrote:  
 
 


The project file won't compile because it seems to be missing some header files and possibly a lot more..

sndfile.h can't be found, nor can imbe_vocoder.h and IMBEFEC.h and probably other files.

What else needs to be installed so this can be compiled ?

**Comment by rogerclarkmelbourne** [comment]
Thanks Jonathan

I'll give that a try.  I am building on Windows using Visual Studio, and I'll need to figure out if libsnd is necessary. 
I see in your readme.md it says libsnd is necessary fro Linux, but I suspect its probably also needed for Windows as well.

If I get it working, I'll try to do a PR to update your readme with instructions to build it on Windows

**Comment by rogerclarkmelbourne** [comment]
Hi Jonathan

I've submitted a PR that resolves the issues I was having

https://github.com/g4klx/AMBETools/pull/3

I have not tested whether this will compile on Linux but it should be OK, because sndfile.h should be included on non-Windows builds

I think the readme is still a bit confusing with regards to the use of the software imbe encoder.

It looks like the software encoder is always used for P25 unless the code is built specifically to to use the DVSI USB3000-P25  dongle, but the doesn't make this clear.

Its a shame the IMBE enoder can't be used for all the modes, but I don't know enough about the differences between IMBE and AMBE to know if they are totally different or similar..

I can see that the P25 encoded files are exactly twice the size of the DMR AMBE files encoded using a dongle.

**Comment by g4klx** [comment]
Hi Roger
As the README says, you need a special piece of hardware from DVSI to do P25 conversions, this is horribly expensive, and I don't have one. It works the same as a standard AMBE dongle but with a few extra modes to support P25. Luckily there is an open source P25 vocoder which can be used with good results. Thankfully the P25 IMBE vocoder is thoroughly specified in the P25 specifications.
The instructions mention that IMBE is done via the software vocoder by default so I see no reason to update them.
The IMBE vocoder is a full rate vocoder, and their is an equivalent (but incompatible) with the full-rate AMBE vocoder in the standard DVSI chip. Being full rate it uses more bytes than the standard AMBE vocoders that are used elsewhere, but they do sound nicer too.
If you want to start a project to do an open source vocoder for D-Star or DMR then please go ahead, however i believe the legality of this is dubious and I don't want get involved.
I tested a Linux compile, all seems fine.
Jonathan  G4KLX

    On Monday, 25 May 2020, 02:42:10 BST, Roger Clark <notifications@github.com> wrote:  
 
 


Hi Jonathan

I've submitted a PR that resolves the issues I was having

#3

I have not tested whether this will compile on Linux but it should be OK, because sndfile.h should be included on non-Windows builds

I do still have one question however...

The readme states...


By default the open source vocoder is used, and the -p, -r and -s options are not used.


However on is the -p option is not specified it is defaulted to /dev/ttyUSB0 and since this can't be opened on Windows this gives an error.

It looks like the software vocoder is possibly only used for P25 and the external dongle is only used for dmr and dstar

If this is the case, and the software vocoder can't be used for those modes, then the usage instructions etc need to be changed.

I'm curios to know whether the software vocoder could be used for other modes if things like the audio block size and frame size are changed.
The sizes used do not look like they are compatible with DMR i.e 60mS input audio slices generate 27 bytes of output.
(Or potentially the underlying vocoder may really be 20ms input audio slices to 9 bytes of output, as I have seen 9 byte blocks of ambe bytes for silence used on various projects)

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I don't have any DVSI dongles, but I know someone who does (VK7ZCR), and he was going to convert the files to AMBE for me.

However, in the end, I decided to add some functionality to the OpenGD77 firmware CPS interface so that the radio can do the encoding.
The interface is a bit clunky, but it serves its purpose for me, of creating AMBE files which will be used for voice prompts in the radio, so that the firmware can be used by the visually impaired.
